# Prometheus监控配置 - 认证中间件性能指标

# 全局配置
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'auth-middleware'
    environment: 'production'

# 告警规则文件
rule_files:
  - 'auth_alerts.yml'

# 抓取配置
scrape_configs:
  # 认证中间件指标
  - job_name: 'auth-middleware'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'localhost:8080'
        - 'localhost:8081'
        - 'localhost:8082'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'

  # Node Exporter（系统指标）
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  # 应用程序指标
  - job_name: 'application'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['localhost:8080']
    metric_relabel_configs:
      # 重命名指标
      - source_labels: [__name__]
        regex: 'auth_(.*)'
        target_label: __name__
        replacement: 'middleware_auth_${1}'

# 远程写入配置（可选）
remote_write:
  - url: "http://localhost:9090/api/v1/write"
    queue_config:
      capacity: 10000
      max_shards: 5
      min_shards: 1
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms